FROM node:12.2.0-alpine as react-build

WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH

COPY package*.json /frontend/
RUN npm install --silent

COPY . .
RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=react-build /frontend/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]