services:
    - docker

script:
    - docker-compose up --build -d
    - docker-compose up -d backend
    - docker ps -a
    - sleep 30 && docker exec backend pytest
after_success:
    - docker exec backend coveralls
before_install:
    - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
      -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
      branch: master
