version: '3.7'

services:
  db:
    image: kartoza/postgis
    volumes:
        - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DBNAME: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
  backend:
    build: ./backend
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app:/code
    environment:
        DJANGO_SETTINGS_MODULE: conf.settings
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres_data: