version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.1
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=roni.lindholm@gmail.com"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
    restart: unless-stopped
    labels:
      # Redirect all HTTP to HTTPS permanently
      - traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http_catchall.entrypoints=web
      - traefik.http.routers.http_catchall.middlewares=https_redirect
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www.helka.dog/(.*)
      - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://helka.dog/$${1}
      - traefik.http.middlewares.www-redirect.redirectregex.permanent=true
      - traefik.http.routers.http-catchallwww.middlewares=www-redirect
      - traefik.http.routers.http-catchallwww.tls=true
      - traefik.http.routers.http-catchallwww.tls.certresolver=le
      - traefik.http.routers.http-catchallwww.rule=Host(`www.helka.dog`)
  db:
    image: kartoza/postgis
    volumes:
        - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DBNAME: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    expose:
      - 5432
  backend:
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python /code/manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./backend/app:/code
      - ./backend/logs:/code/logs
    restart: unless-stopped
    environment:
        DJANGO_SETTINGS_MODULE: conf.settings
    depends_on:
      - db
    expose:
      - 8000
    labels:
      - traefik.http.routers.backend.rule=(Host(`helka.dog`) && PathPrefix(`/api`))
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=le
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-prod
    volumes:
      - ./frontend:/frontend
    restart: unless-stopped
    expose:
      - 80
    links:
      - backend
      - reverse-proxy
    labels:
      - traefik.http.routers.frontend.rule=Host(`helka.dog`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=le
  h02-tracker:
    build: ./tracker-server
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./tracker-server:/code
    depends_on:
      - backend
    links:
      - backend
  redis:
    image: redis:5.0-alpine
    volumes:
        - redis_data:/data
    expose:
      - 6379
  celery:
    build: ./backend
    command: ["celery", "worker", "-A", "conf.celery"]
    volumes:
      - ./backend/app:/code
    depends_on:
      - redis
      - db
      - backend
volumes:
  postgres_data:
  redis_data:
