# Generated by Django 3.0.3 on 2020-03-15 18:13

from django.db import migrations

import auth_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20200315_1708'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_app.models.CustomUserManager()),
            ],
        ),
    ]
