# Generated by Django 3.0.3 on 2020-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_interval',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
