# Generated by Django 3.0.3 on 2020-03-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200302_1204'),
        ('tracking', '0002_auto_20200302_0719'),
    ]

    operations = [
    ]
