# Generated by Django 3.0.3 on 2020-03-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_merge_20200302_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
