# Generated by Django 3.0.3 on 2020-03-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tracker_id',
            field=models.CharField(default='tracker-id', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
