# Generated by Django 3.0.3 on 2020-03-18 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20200318_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
        migrations.AddField(
            model_name='track',
            name='track',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
