# Generated by Django 3.0.3 on 2020-03-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20200318_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
    ]
