# Generated by Django 3.0.3 on 2020-03-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_track_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracking.Device'),
            preserve_default=False,
        ),
    ]
