# Generated by Django 3.0.3 on 2020-03-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_track_device'),
        ('tracking', '0010_remove_device_user'),
    ]

    operations = [
    ]
